// Generates src/api/generated/schema.d.ts from the committed OpenAPI contract (read-only input).
//   node scripts/gen-api.mjs          write the file
//   node scripts/gen-api.mjs --check  fail when the committed file is stale (CI)
// The spec is owned by the API slice (packages/contracts); this app only reads it.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

const here = dirname(fileURLToPath(import.meta.url));
const spec = resolve(here, "../../../packages/contracts/openapi/dwaar.v1.json");
const out = resolve(here, "../src/api/generated/schema.d.ts");
const check = process.argv.includes("--check");

const ast = await openapiTS(new URL(`file://${spec}`));
const header =
  "// GENERATED by scripts/gen-api.mjs from packages/contracts/openapi/dwaar.v1.json. Do not edit.\n" +
  "/* eslint-disable */\n";
const next = header + astToString(ast);

if (check) {
  const current = existsSync(out) ? readFileSync(out, "utf8") : "";
  if (current !== next) {
    console.error("src/api/generated/schema.d.ts is stale; run `pnpm gen:api`.");
    process.exit(1);
  }
  console.log("generated API types are up to date");
} else {
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, next);
  console.log(`wrote ${out} (${next.length} bytes) from ${readFileSync(spec).length}-byte spec`);
}
