// Generates the typed API contract INTO this app from the read-only OpenAPI file (packages/contracts is never edited).
//   node scripts/gen-api.mjs          write src/api/schema.d.ts
//   node scripts/gen-api.mjs --check  fail when the committed file is stale
import openapiTS, { astToString } from "openapi-typescript";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const spec = resolve(here, "../../../packages/contracts/openapi/dwaar.v1.json");
const out = resolve(here, "../src/api/schema.d.ts");
const header = "// GENERATED by scripts/gen-api.mjs from packages/contracts/openapi/dwaar.v1.json. Do not edit.\n/* eslint-disable */\n";

const ast = await openapiTS(pathToFileURL(spec));
const next = header + astToString(ast);
if (process.argv.includes("--check")) {
  const current = existsSync(out) ? readFileSync(out, "utf8") : "";
  if (current !== next) {
    console.error("src/api/schema.d.ts is stale: run `pnpm --filter @dwaar/admin-web gen:api`");
    process.exit(1);
  }
  console.log("api types up to date");
} else {
  writeFileSync(out, next);
  console.log(`wrote ${out}`);
}
