package app.dwaar.guard.core

import app.dwaar.guard.core.canonical.CanonicalJson
import app.dwaar.guard.core.canonical.CanonicalJsonException
import app.dwaar.guard.core.edge.Ed25519
import app.dwaar.guard.core.edge.EdgeEvent
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertNotEquals
import org.junit.jupiter.api.Assertions.assertThrows
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

/**
 * Cross-language golden vectors generated by the Python reference (tools/dev/android/gen_golden_vectors.py ->
 * dwaar_common.events / dwaar_common.signing). REQ: EDGE-02, EDGE-03. Byte-identical canonical JSON, hashes and signatures.
 */
class GoldenVectorTest {
    private val doc: JsonObject = Json.parseToJsonElement(
        javaClass.getResourceAsStream("/golden/edge_vectors.json")!!.readBytes().toString(Charsets.UTF_8),
    ).jsonObject

    private fun hex(s: String) = ByteArray(s.length / 2) { s.substring(it * 2, it * 2 + 2).toInt(16).toByte() }

    @Test fun canonicalJsonAndHashesMatchPython() {
        val cases = doc.getValue("canonical_cases").jsonArray
        assertTrue(cases.size >= 8)
        for (c in cases) {
            val o = c.jsonObject
            val input = Json.parseToJsonElement(o.getValue("input_json").jsonPrimitive.content)
            assertEquals(o.getValue("canonical").jsonPrimitive.content, CanonicalJson.encodeToString(input), "canonical of ${o["input_json"]}")
            val sha = o.getValue("sha256_hex")
            if (sha !is JsonNull) {
                assertEquals(sha.jsonPrimitive.content, CanonicalJson.payloadHash(input.jsonObject).removePrefix("sha256:"))
            }
        }
    }

    @Test fun inputsPythonRejectsAreRejected() {
        for (r in doc.getValue("reject_cases").jsonArray) {
            val v = Json.parseToJsonElement(r.jsonPrimitive.content)
            assertThrows(CanonicalJsonException::class.java) { CanonicalJson.encode(v) }
        }
    }

    @Test fun edgeEventsSignAndHashIdenticallyToPython() {
        val events = doc.getValue("edge_events").jsonArray
        assertEquals(3, events.size)
        for (e in events) {
            val o = e.jsonObject
            val seed = hex(o.getValue("seed_hex").jsonPrimitive.content)
            val wire = o.getValue("unsigned_wire").jsonObject
            val ev = EdgeEvent.fromWire(JsonObject(wire + ("signature" to JsonNull)))
            assertEquals(o.getValue("payload_hash").jsonPrimitive.content, ev.payloadHash)
            assertTrue(ev.payloadHashMatches())
            assertEquals(o.getValue("signing_bytes").jsonPrimitive.content, String(ev.signingBytes(), Charsets.UTF_8))

            val key = Ed25519.privateKeyFromSeed(seed)
            val signed = ev.sign(key)
            assertEquals(o.getValue("signature").jsonPrimitive.content, signed.signature, "Ed25519 signature must match Python byte for byte")
            assertEquals(o.getValue("canonical_full").jsonPrimitive.content, String(signed.canonicalBytes(), Charsets.UTF_8))

            val pub = Ed25519.publicKeyFromRaw(Ed25519.b64urlDecode(o.getValue("public_key_b64url").jsonPrimitive.content))
            assertTrue(signed.verify(pub))
            assertEquals(o.getValue("key_id").jsonPrimitive.content, Ed25519.keyId(Ed25519.rawPublicKey(pub)))
        }
    }

    @Test fun buildComputesTheSameWireAsPython() {
        val o = doc.getValue("edge_events").jsonArray[0].jsonObject
        val wire = o.getValue("unsigned_wire").jsonObject
        val rebuilt = EdgeEvent.build(
            eventId = wire.getValue("event_id").jsonPrimitive.content,
            societyId = wire.getValue("society_id").jsonPrimitive.content,
            deviceId = wire.getValue("device_id").jsonPrimitive.content,
            seq = 18452, entityId = wire.getValue("entity_id").jsonPrimitive.content, entityVersion = 2, type = "EntryObserved",
            policyVersion = 913, payload = wire.getValue("payload").jsonObject,
            occurredAt = java.time.Instant.parse("2026-10-05T13:41:07.250Z"), clockUncertaintyMs = 120,
        )
        assertEquals(o.getValue("signing_bytes").jsonPrimitive.content, String(rebuilt.signingBytes(), Charsets.UTF_8))
        // sub-millisecond precision is dropped exactly like the Python model does
        val withNanos = EdgeEvent.build(
            rebuilt.eventId, rebuilt.societyId, rebuilt.deviceId, 18452, rebuilt.entityId, 2, "EntryObserved", 913, rebuilt.payload,
            java.time.Instant.parse("2026-10-05T13:41:07.250999Z"), 120,
        )
        assertEquals(rebuilt.occurredAt, withNanos.occurredAt)
    }

    @Test fun tamperingBreaksTheSignature() {
        val o = doc.getValue("edge_events").jsonArray[0].jsonObject
        val ev = EdgeEvent.fromWire(JsonObject(o.getValue("unsigned_wire").jsonObject + ("signature" to JsonPrimitive(o.getValue("signature").jsonPrimitive.content))))
        val pub = Ed25519.publicKeyFromRaw(Ed25519.b64urlDecode(o.getValue("public_key_b64url").jsonPrimitive.content))
        assertTrue(ev.verify(pub))
        assertFalse(ev.copy(seq = ev.seq + 1).verify(pub))
        assertFalse(ev.copy(eventId = "0192f3b2-1111-7aaa-8bbb-ccccdddd9999").verify(pub))
        assertFalse(ev.copy(signature = null).verify(pub))
        assertNotEquals(ev.signature, ev.copy(seq = ev.seq + 1).sign(Ed25519.privateKeyFromSeed(hex(o.getValue("seed_hex").jsonPrimitive.content))).signature)
        assertEquals(JsonArray(emptyList()), Json.parseToJsonElement("[]"))
    }
}
