#!/usr/bin/env node
// Generates packages/i18n/src/keys.ts (key union + params map) and src/catalogs.ts (static JSON imports)
// from packages/i18n/locales. English is the source of truth. Run: node tools/gen_i18n_keys.mjs [--check]
import { readFileSync, readdirSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "packages", "i18n");
const langs = ["en", "hi", "mr"];
const namespaces = readdirSync(join(root, "locales", "en"))
  .filter((f) => f.endsWith(".json"))
  .map((f) => f.slice(0, -5))
  .sort();

const entries = [];
for (const ns of namespaces) {
  const data = JSON.parse(readFileSync(join(root, "locales", "en", `${ns}.json`), "utf8"));
  for (const k of Object.keys(data).sort()) {
    const params = [...new Set([...data[k].matchAll(/\{([A-Za-z_][A-Za-z0-9_]*)\}/g)].map((m) => m[1]))].sort();
    entries.push([`${ns}.${k}`, params]);
  }
}

const header = "// GENERATED by tools/gen_i18n_keys.mjs from locales/en. Do not edit.\n";
const keys =
  header +
  `export const NAMESPACES = ${JSON.stringify(namespaces)} as const;\n` +
  "export type Namespace = (typeof NAMESPACES)[number];\n\n" +
  "export interface KeyParams {\n" +
  entries.map(([k, p]) => `  ${JSON.stringify(k)}: ${p.length ? `{ ${p.map((x) => `${x}: string | number`).join("; ")} }` : "undefined"};`).join("\n") +
  "\n}\n\nexport type I18nKey = keyof KeyParams;\n\n" +
  `export const ALL_KEYS: readonly I18nKey[] = ${JSON.stringify(entries.map(([k]) => k), null, 2)};\n`;

const idents = (l, ns) => `${l}_${ns}`;
let cat = header + "/* eslint-disable */\n";
for (const l of langs) for (const ns of namespaces) cat += `import ${idents(l, ns)} from "../locales/${l}/${ns}.json";\n`;
cat += "\nexport type Catalog = Record<string, Record<string, string>>;\n\nexport const CATALOGS: Record<string, Catalog> = {\n";
for (const l of langs) {
  cat += `  ${l}: {\n` + namespaces.map((ns) => `    ${ns}: ${idents(l, ns)},`).join("\n") + "\n  },\n";
}
cat += "};\n";

const out = [[join(root, "src", "keys.ts"), keys], [join(root, "src", "catalogs.ts"), cat]];
if (process.argv.includes("--check")) {
  const stale = out.filter(([p, c]) => !existsSync(p) || readFileSync(p, "utf8") !== c);
  if (stale.length) { console.error("stale generated files:", stale.map(([p]) => p).join(", ")); process.exit(1); }
  console.log("i18n keys up to date");
} else {
  for (const [p, c] of out) writeFileSync(p, c);
  console.log(`generated ${entries.length} keys across ${namespaces.length} namespaces`);
}
