// GENERATED by tools/gen_i18n_keys.mjs from locales/en. Do not edit.
/* eslint-disable */
import en_common from "../locales/en/common.json";
import en_consent from "../locales/en/consent.json";
import en_errors from "../locales/en/errors.json";
import en_finance from "../locales/en/finance.json";
import en_guard from "../locales/en/guard.json";
import en_notifications from "../locales/en/notifications.json";
import en_ops from "../locales/en/ops.json";
import en_resident from "../locales/en/resident.json";
import en_states from "../locales/en/states.json";
import en_visitor from "../locales/en/visitor.json";
import hi_common from "../locales/hi/common.json";
import hi_consent from "../locales/hi/consent.json";
import hi_errors from "../locales/hi/errors.json";
import hi_finance from "../locales/hi/finance.json";
import hi_guard from "../locales/hi/guard.json";
import hi_notifications from "../locales/hi/notifications.json";
import hi_ops from "../locales/hi/ops.json";
import hi_resident from "../locales/hi/resident.json";
import hi_states from "../locales/hi/states.json";
import hi_visitor from "../locales/hi/visitor.json";
import mr_common from "../locales/mr/common.json";
import mr_consent from "../locales/mr/consent.json";
import mr_errors from "../locales/mr/errors.json";
import mr_finance from "../locales/mr/finance.json";
import mr_guard from "../locales/mr/guard.json";
import mr_notifications from "../locales/mr/notifications.json";
import mr_ops from "../locales/mr/ops.json";
import mr_resident from "../locales/mr/resident.json";
import mr_states from "../locales/mr/states.json";
import mr_visitor from "../locales/mr/visitor.json";

export type Catalog = Record<string, Record<string, string>>;

export const CATALOGS: Record<string, Catalog> = {
  en: {
    common: en_common,
    consent: en_consent,
    errors: en_errors,
    finance: en_finance,
    guard: en_guard,
    notifications: en_notifications,
    ops: en_ops,
    resident: en_resident,
    states: en_states,
    visitor: en_visitor,
  },
  hi: {
    common: hi_common,
    consent: hi_consent,
    errors: hi_errors,
    finance: hi_finance,
    guard: hi_guard,
    notifications: hi_notifications,
    ops: hi_ops,
    resident: hi_resident,
    states: hi_states,
    visitor: hi_visitor,
  },
  mr: {
    common: mr_common,
    consent: mr_consent,
    errors: mr_errors,
    finance: mr_finance,
    guard: mr_guard,
    notifications: mr_notifications,
    ops: mr_ops,
    resident: mr_resident,
    states: mr_states,
    visitor: mr_visitor,
  },
};
