// GENERATED by tools/gen_i18n_keys.mjs from locales/en. Do not edit.
export const NAMESPACES = ["common","consent","errors","finance","guard","notifications","ops","resident","states","visitor"] as const;
export type Namespace = (typeof NAMESPACES)[number];

export interface KeyParams {
  "common.action.back": undefined;
  "common.action.call": undefined;
  "common.action.cancel": undefined;
  "common.action.close": undefined;
  "common.action.confirm": undefined;
  "common.action.done": undefined;
  "common.action.help": undefined;
  "common.action.next": undefined;
  "common.action.ok": undefined;
  "common.action.retry": undefined;
  "common.action.save": undefined;
  "common.action.sign_out": undefined;
  "common.answer.no": undefined;
  "common.answer.yes": undefined;
  "common.app.name": undefined;
  "common.language.en": undefined;
  "common.language.hi": undefined;
  "common.language.label": undefined;
  "common.language.mr": undefined;
  "common.status.loading": undefined;
  "common.time.just_now": undefined;
  "common.time.minutes_ago": { minutes: string | number };
  "common.unit.label": { unit: string | number };
  "consent.review.flag": undefined;
  "consent.stub.consent.body": undefined;
  "consent.stub.consent.title": undefined;
  "consent.stub.notice.body": undefined;
  "consent.stub.notice.title": undefined;
  "errors.already_decided": undefined;
  "errors.dependency_unavailable": undefined;
  "errors.duplicate_payload_mismatch": undefined;
  "errors.invalid_schema": undefined;
  "errors.legal_pack_not_approved": undefined;
  "errors.missing_tax_config": undefined;
  "errors.not_authorised": undefined;
  "errors.not_found": undefined;
  "errors.policy_violation": undefined;
  "errors.rate_limited": { retry_after_seconds: string | number };
  "errors.request_expired": undefined;
  "errors.request_id.label": { request_id: string | number };
  "errors.stale_version": undefined;
  "errors.unauthenticated": undefined;
  "errors.unknown": { request_id: string | number };
  "finance.action.pay_now": undefined;
  "finance.bill.due": { amount: string | number; date: string | number };
  "finance.bill.title": undefined;
  "finance.essential_services.note": undefined;
  "finance.receipt.number": { number: string | number };
  "finance.receipt.title": undefined;
  "finance.settlement.failed": undefined;
  "finance.settlement.pending": undefined;
  "finance.settlement.settled": undefined;
  "finance.status.paid": undefined;
  "finance.status.partially_paid": { paid: string | number; total: string | number };
  "finance.status.unpaid": undefined;
  "guard.banner.offline": undefined;
  "guard.banner.online": undefined;
  "guard.banner.policy_age": { minutes: string | number };
  "guard.banner.policy_stale": undefined;
  "guard.commit.saved": undefined;
  "guard.decision.allow": undefined;
  "guard.decision.deny": undefined;
  "guard.handover.check_parcel": undefined;
  "guard.handover.check_person": undefined;
  "guard.handover.check_unit": undefined;
  "guard.handover.confirm": undefined;
  "guard.handover.title": undefined;
  "guard.incident.emergency": undefined;
  "guard.incident.report": undefined;
  "guard.nav.incident": undefined;
  "guard.nav.inside": undefined;
  "guard.nav.parcels": undefined;
  "guard.nav.scan": undefined;
  "guard.nav.shift": undefined;
  "guard.queue.empty": undefined;
  "guard.queue.pending": { count: string | number };
  "guard.shift.end": undefined;
  "guard.shift.start": undefined;
  "guard.tile.delivery": undefined;
  "guard.tile.guest": undefined;
  "guard.tile.service": undefined;
  "guard.training.banner": undefined;
  "guard.training.complete": undefined;
  "guard.training.scenario.emergency": undefined;
  "guard.training.scenario.invited_visitor": undefined;
  "guard.training.scenario.no_response": undefined;
  "guard.training.scenario.outage": undefined;
  "guard.training.scenario.unannounced_guest": undefined;
  "guard.visitor.call_resident": undefined;
  "guard.visitor.no_response": undefined;
  "guard.visitor.waiting_approval": undefined;
  "notifications.approval.decided.body": { decision: string | number; visitor: string | number };
  "notifications.approval.decided.title": undefined;
  "notifications.approval.escalation.body": { minutes: string | number };
  "notifications.approval.escalation.title": undefined;
  "notifications.approval.expired.body": undefined;
  "notifications.approval.expired.title": undefined;
  "notifications.approval.request.body": { unit: string | number; visitor: string | number };
  "notifications.approval.request.lockscreen.body": undefined;
  "notifications.approval.request.lockscreen.title": undefined;
  "notifications.approval.request.title": undefined;
  "notifications.channel.emergency.title": undefined;
  "notifications.channel.security.description": undefined;
  "notifications.setting.show_identity_lockscreen": undefined;
  "ops.helpdesk.state.assigned": undefined;
  "ops.helpdesk.state.closed": undefined;
  "ops.helpdesk.state.in_progress": undefined;
  "ops.helpdesk.state.open": undefined;
  "ops.helpdesk.state.reopened": undefined;
  "ops.helpdesk.state.resolved": undefined;
  "ops.helpdesk.state.waiting_resident": undefined;
  "ops.sla.breached": { hours: string | number };
  "ops.sla.due_in": { hours: string | number };
  "ops.sla.on_track": undefined;
  "resident.approval.approve": undefined;
  "resident.approval.deny": undefined;
  "resident.approval.not_entered_note": undefined;
  "resident.approval.visitor_at_gate": { visitor: string | number };
  "resident.fallback.call_guard": undefined;
  "resident.fallback.call_note": undefined;
  "resident.home.action.approve": undefined;
  "resident.home.action.invite": undefined;
  "resident.home.action.pay_dues": undefined;
  "resident.home.action.report_issue": undefined;
  "resident.home.operational_messages": undefined;
  "resident.home.pending_approval": undefined;
  "resident.home.title": undefined;
  "resident.state.empty": undefined;
  "resident.state.expired": undefined;
  "resident.state.loading": undefined;
  "resident.state.offline": undefined;
  "resident.state.permission_denied": undefined;
  "resident.support.raise": undefined;
  "states.local.saved_awaiting_sync": undefined;
  "states.local.synced": undefined;
  "states.parcel.at_gate": undefined;
  "states.parcel.handed_over": undefined;
  "states.payment.paid": undefined;
  "states.payment.received_settlement_pending": undefined;
  "states.payment.settled": undefined;
  "states.visit.approved": undefined;
  "states.visit.denied": undefined;
  "states.visit.entered": undefined;
  "states.visit.expired": undefined;
  "states.visit.no_response": undefined;
  "states.visit.submitted": undefined;
  "visitor.consent.accept": undefined;
  "visitor.consent.decline": undefined;
  "visitor.consent.title": undefined;
  "visitor.notice.body": undefined;
  "visitor.notice.title": undefined;
  "visitor.pass.expired": undefined;
  "visitor.pass.expiry": { time: string | number };
  "visitor.rights.link": undefined;
}

export type I18nKey = keyof KeyParams;

export const ALL_KEYS: readonly I18nKey[] = [
  "common.action.back",
  "common.action.call",
  "common.action.cancel",
  "common.action.close",
  "common.action.confirm",
  "common.action.done",
  "common.action.help",
  "common.action.next",
  "common.action.ok",
  "common.action.retry",
  "common.action.save",
  "common.action.sign_out",
  "common.answer.no",
  "common.answer.yes",
  "common.app.name",
  "common.language.en",
  "common.language.hi",
  "common.language.label",
  "common.language.mr",
  "common.status.loading",
  "common.time.just_now",
  "common.time.minutes_ago",
  "common.unit.label",
  "consent.review.flag",
  "consent.stub.consent.body",
  "consent.stub.consent.title",
  "consent.stub.notice.body",
  "consent.stub.notice.title",
  "errors.already_decided",
  "errors.dependency_unavailable",
  "errors.duplicate_payload_mismatch",
  "errors.invalid_schema",
  "errors.legal_pack_not_approved",
  "errors.missing_tax_config",
  "errors.not_authorised",
  "errors.not_found",
  "errors.policy_violation",
  "errors.rate_limited",
  "errors.request_expired",
  "errors.request_id.label",
  "errors.stale_version",
  "errors.unauthenticated",
  "errors.unknown",
  "finance.action.pay_now",
  "finance.bill.due",
  "finance.bill.title",
  "finance.essential_services.note",
  "finance.receipt.number",
  "finance.receipt.title",
  "finance.settlement.failed",
  "finance.settlement.pending",
  "finance.settlement.settled",
  "finance.status.paid",
  "finance.status.partially_paid",
  "finance.status.unpaid",
  "guard.banner.offline",
  "guard.banner.online",
  "guard.banner.policy_age",
  "guard.banner.policy_stale",
  "guard.commit.saved",
  "guard.decision.allow",
  "guard.decision.deny",
  "guard.handover.check_parcel",
  "guard.handover.check_person",
  "guard.handover.check_unit",
  "guard.handover.confirm",
  "guard.handover.title",
  "guard.incident.emergency",
  "guard.incident.report",
  "guard.nav.incident",
  "guard.nav.inside",
  "guard.nav.parcels",
  "guard.nav.scan",
  "guard.nav.shift",
  "guard.queue.empty",
  "guard.queue.pending",
  "guard.shift.end",
  "guard.shift.start",
  "guard.tile.delivery",
  "guard.tile.guest",
  "guard.tile.service",
  "guard.training.banner",
  "guard.training.complete",
  "guard.training.scenario.emergency",
  "guard.training.scenario.invited_visitor",
  "guard.training.scenario.no_response",
  "guard.training.scenario.outage",
  "guard.training.scenario.unannounced_guest",
  "guard.visitor.call_resident",
  "guard.visitor.no_response",
  "guard.visitor.waiting_approval",
  "notifications.approval.decided.body",
  "notifications.approval.decided.title",
  "notifications.approval.escalation.body",
  "notifications.approval.escalation.title",
  "notifications.approval.expired.body",
  "notifications.approval.expired.title",
  "notifications.approval.request.body",
  "notifications.approval.request.lockscreen.body",
  "notifications.approval.request.lockscreen.title",
  "notifications.approval.request.title",
  "notifications.channel.emergency.title",
  "notifications.channel.security.description",
  "notifications.setting.show_identity_lockscreen",
  "ops.helpdesk.state.assigned",
  "ops.helpdesk.state.closed",
  "ops.helpdesk.state.in_progress",
  "ops.helpdesk.state.open",
  "ops.helpdesk.state.reopened",
  "ops.helpdesk.state.resolved",
  "ops.helpdesk.state.waiting_resident",
  "ops.sla.breached",
  "ops.sla.due_in",
  "ops.sla.on_track",
  "resident.approval.approve",
  "resident.approval.deny",
  "resident.approval.not_entered_note",
  "resident.approval.visitor_at_gate",
  "resident.fallback.call_guard",
  "resident.fallback.call_note",
  "resident.home.action.approve",
  "resident.home.action.invite",
  "resident.home.action.pay_dues",
  "resident.home.action.report_issue",
  "resident.home.operational_messages",
  "resident.home.pending_approval",
  "resident.home.title",
  "resident.state.empty",
  "resident.state.expired",
  "resident.state.loading",
  "resident.state.offline",
  "resident.state.permission_denied",
  "resident.support.raise",
  "states.local.saved_awaiting_sync",
  "states.local.synced",
  "states.parcel.at_gate",
  "states.parcel.handed_over",
  "states.payment.paid",
  "states.payment.received_settlement_pending",
  "states.payment.settled",
  "states.visit.approved",
  "states.visit.denied",
  "states.visit.entered",
  "states.visit.expired",
  "states.visit.no_response",
  "states.visit.submitted",
  "visitor.consent.accept",
  "visitor.consent.decline",
  "visitor.consent.title",
  "visitor.notice.body",
  "visitor.notice.title",
  "visitor.pass.expired",
  "visitor.pass.expiry",
  "visitor.rights.link"
];
