// GENERATED by tools/gen_i18n_keys.mjs from locales/en. Do not edit.
export const NAMESPACES = ["ai","common","community","consent","errors","finance","guard","notifications","ops","parcels","resident","shifts","staff","states","visitor"] as const;
export type Namespace = (typeof NAMESPACES)[number];

export interface KeyParams {
  "ai.complaint.choose_location": undefined;
  "ai.complaint.confirm_location": { location: string | number };
  "ai.complaint.consent_speech": undefined;
  "ai.complaint.emergency": undefined;
  "ai.complaint.limit_60s": undefined;
  "ai.fallback.budget_exhausted": undefined;
  "ai.fallback.kill_switch": undefined;
  "ai.fallback.not_enabled": undefined;
  "ai.fallback.ordinary_path": undefined;
  "ai.feature.bill_anomaly": undefined;
  "ai.feature.complaint": undefined;
  "ai.feature.handover": undefined;
  "ai.feature.notice": undefined;
  "ai.feature.notification_health": undefined;
  "ai.feature.poll": undefined;
  "ai.feature.translation": undefined;
  "ai.feature.triage": undefined;
  "ai.label.ai_draft": undefined;
  "ai.label.correction": undefined;
  "ai.label.declining": undefined;
  "ai.label.human_review": undefined;
  "ai.label.original_text": undefined;
  "ai.label.reasons": undefined;
  "ai.label.simulation": undefined;
  "ai.label.sources": undefined;
  "ai.label.what_will_be_saved": undefined;
  "ai.notice.needs_approval": undefined;
  "ai.notice.threat_flag": { reason: string | number };
  "ai.notification_health.disclaimer": undefined;
  "ai.promise.no_ads": undefined;
  "ai.promise.no_gate": undefined;
  "ai.promise.no_money": undefined;
  "ai.promise.no_training": undefined;
  "ai.proposal.confirm": undefined;
  "ai.proposal.confirmed": undefined;
  "ai.proposal.discard": undefined;
  "ai.proposal.edit": undefined;
  "ai.proposal.expired": undefined;
  "ai.proposal.preview_title": undefined;
  "ai.proposal.stale": undefined;
  "ai.translation.legal_review": undefined;
  "ai.translation.original_shown": undefined;
  "common.action.back": undefined;
  "common.action.call": undefined;
  "common.action.cancel": undefined;
  "common.action.close": undefined;
  "common.action.confirm": undefined;
  "common.action.done": undefined;
  "common.action.help": undefined;
  "common.action.next": undefined;
  "common.action.ok": undefined;
  "common.action.retry": undefined;
  "common.action.save": undefined;
  "common.action.sign_out": undefined;
  "common.answer.no": undefined;
  "common.answer.yes": undefined;
  "common.app.name": undefined;
  "common.language.en": undefined;
  "common.language.hi": undefined;
  "common.language.label": undefined;
  "common.language.mr": undefined;
  "common.status.loading": undefined;
  "common.time.just_now": undefined;
  "common.time.minutes_ago": { minutes: string | number };
  "common.unit.label": { unit: string | number };
  "community.document.access.all_residents": undefined;
  "community.document.access.committee": undefined;
  "community.document.access.managers": undefined;
  "community.document.access.owners": undefined;
  "community.document.authority": { authority: string | number };
  "community.document.download.expires": { seconds: string | number };
  "community.document.effective_from": { date: string | number };
  "community.document.scan.clean": undefined;
  "community.document.scan.infected": undefined;
  "community.document.scan.simulation": undefined;
  "community.document.scan.unavailable": undefined;
  "community.document.sha256": undefined;
  "community.document.type.audit_report": undefined;
  "community.document.type.bye_laws": undefined;
  "community.document.type.circular": undefined;
  "community.document.type.minutes": undefined;
  "community.document.type.other": undefined;
  "community.document.type.policy": undefined;
  "community.document.upload.unsupported": undefined;
  "community.emergency.channel": undefined;
  "community.emergency.no_ads": undefined;
  "community.emergency.rate_limited": undefined;
  "community.notice.acknowledge": undefined;
  "community.notice.ai_draft.label": undefined;
  "community.notice.ai_draft.needs_approval": undefined;
  "community.notice.audience.block": undefined;
  "community.notice.audience.role": undefined;
  "community.notice.audience.society": undefined;
  "community.notice.audience.unit": undefined;
  "community.notice.kind.emergency": undefined;
  "community.notice.kind.general": undefined;
  "community.notice.kind.legal": undefined;
  "community.notice.kind.safety": undefined;
  "community.notice.original": { language: string | number };
  "community.notice.published_immutable": undefined;
  "community.notice.state.approved": undefined;
  "community.notice.state.archived": undefined;
  "community.notice.state.draft": undefined;
  "community.notice.state.published": undefined;
  "community.notice.state.scheduled": undefined;
  "community.notice.state.superseded": undefined;
  "community.notice.translation.machine_drafted": undefined;
  "community.notice.translation.review_required": undefined;
  "community.notice.translation.reviewed": undefined;
  "community.notice.translation.unreviewed": undefined;
  "community.poll.answered": undefined;
  "community.poll.non_binding": undefined;
  "community.poll.non_binding_hint": undefined;
  "community.poll.owners_only": undefined;
  "community.poll.state.closed": undefined;
  "community.poll.state.draft": undefined;
  "community.poll.state.open": undefined;
  "community.poll.visibility.after_close": undefined;
  "community.poll.visibility.live": undefined;
  "community.poll.visibility.managers_only": undefined;
  "community.poll.wording.flagged": undefined;
  "consent.review.flag": undefined;
  "consent.stub.consent.body": undefined;
  "consent.stub.consent.title": undefined;
  "consent.stub.notice.body": undefined;
  "consent.stub.notice.title": undefined;
  "errors.already_decided": undefined;
  "errors.dependency_unavailable": undefined;
  "errors.duplicate_payload_mismatch": undefined;
  "errors.invalid_schema": undefined;
  "errors.legal_pack_not_approved": undefined;
  "errors.missing_tax_config": undefined;
  "errors.not_authorised": undefined;
  "errors.not_found": undefined;
  "errors.policy_violation": undefined;
  "errors.rate_limited": { retry_after_seconds: string | number };
  "errors.request_expired": undefined;
  "errors.request_id.label": { request_id: string | number };
  "errors.stale_version": undefined;
  "errors.unauthenticated": undefined;
  "errors.unknown": { request_id: string | number };
  "finance.action.pay_now": undefined;
  "finance.bill.due": { amount: string | number; date: string | number };
  "finance.bill.title": undefined;
  "finance.essential_services.note": undefined;
  "finance.receipt.number": { number: string | number };
  "finance.receipt.title": undefined;
  "finance.settlement.failed": undefined;
  "finance.settlement.pending": undefined;
  "finance.settlement.settled": undefined;
  "finance.status.paid": undefined;
  "finance.status.partially_paid": { paid: string | number; total: string | number };
  "finance.status.unpaid": undefined;
  "guard.banner.offline": undefined;
  "guard.banner.online": undefined;
  "guard.banner.policy_age": { minutes: string | number };
  "guard.banner.policy_stale": undefined;
  "guard.commit.saved": undefined;
  "guard.decision.allow": undefined;
  "guard.decision.deny": undefined;
  "guard.handover.check_parcel": undefined;
  "guard.handover.check_person": undefined;
  "guard.handover.check_unit": undefined;
  "guard.handover.confirm": undefined;
  "guard.handover.title": undefined;
  "guard.incident.emergency": undefined;
  "guard.incident.report": undefined;
  "guard.nav.incident": undefined;
  "guard.nav.inside": undefined;
  "guard.nav.parcels": undefined;
  "guard.nav.scan": undefined;
  "guard.nav.shift": undefined;
  "guard.queue.empty": undefined;
  "guard.queue.pending": { count: string | number };
  "guard.shift.end": undefined;
  "guard.shift.start": undefined;
  "guard.tile.delivery": undefined;
  "guard.tile.guest": undefined;
  "guard.tile.service": undefined;
  "guard.training.banner": undefined;
  "guard.training.complete": undefined;
  "guard.training.scenario.emergency": undefined;
  "guard.training.scenario.invited_visitor": undefined;
  "guard.training.scenario.no_response": undefined;
  "guard.training.scenario.outage": undefined;
  "guard.training.scenario.unannounced_guest": undefined;
  "guard.visitor.call_resident": undefined;
  "guard.visitor.no_response": undefined;
  "guard.visitor.waiting_approval": undefined;
  "notifications.approval.action.already_decided": undefined;
  "notifications.approval.action.expired": undefined;
  "notifications.approval.decided.body": { decision: string | number; visitor: string | number };
  "notifications.approval.decided.title": undefined;
  "notifications.approval.escalation.body": { minutes: string | number };
  "notifications.approval.escalation.title": undefined;
  "notifications.approval.expired.body": undefined;
  "notifications.approval.expired.title": undefined;
  "notifications.approval.guard_options.title": undefined;
  "notifications.approval.ivr.prompt": undefined;
  "notifications.approval.link.sms": { link: string | number };
  "notifications.approval.link.whatsapp": { link: string | number };
  "notifications.approval.request.body": { unit: string | number; visitor: string | number };
  "notifications.approval.request.lockscreen.body": undefined;
  "notifications.approval.request.lockscreen.title": undefined;
  "notifications.approval.request.title": undefined;
  "notifications.channel.emergency.title": undefined;
  "notifications.channel.security.description": undefined;
  "notifications.diag.apple.focus_allow": undefined;
  "notifications.diag.apple.time_sensitive": undefined;
  "notifications.diag.common.battery": undefined;
  "notifications.diag.common.permission": undefined;
  "notifications.diag.common.test_push": undefined;
  "notifications.diag.disclaimer.no_guarantee": undefined;
  "notifications.diag.oppo.app_launch": undefined;
  "notifications.diag.oppo.battery": undefined;
  "notifications.diag.samsung.battery": undefined;
  "notifications.diag.samsung.sleeping_apps": undefined;
  "notifications.diag.verdict.cannot_tell": undefined;
  "notifications.diag.verdict.needs_attention": undefined;
  "notifications.diag.verdict.no_problem_found": undefined;
  "notifications.diag.vivo.autostart": undefined;
  "notifications.diag.vivo.background_power": undefined;
  "notifications.diag.xiaomi.autostart": undefined;
  "notifications.diag.xiaomi.battery": undefined;
  "notifications.diag.xiaomi.lock_recents": undefined;
  "notifications.digest.weekly.body": undefined;
  "notifications.digest.weekly.title": undefined;
  "notifications.emergency.alert.body": undefined;
  "notifications.emergency.alert.title": undefined;
  "notifications.fallback.call": undefined;
  "notifications.fallback.intercom": undefined;
  "notifications.fallback.provider_outage": undefined;
  "notifications.finance.notice.body": undefined;
  "notifications.finance.notice.title": undefined;
  "notifications.option.deny": undefined;
  "notifications.option.hold": undefined;
  "notifications.option.intercom": undefined;
  "notifications.option.leave_at_gate": undefined;
  "notifications.option.lobby_only": undefined;
  "notifications.setting.show_identity_lockscreen": undefined;
  "notifications.status.actioned": undefined;
  "notifications.status.app_received": undefined;
  "notifications.status.created": undefined;
  "notifications.status.displayed": undefined;
  "notifications.status.expired": undefined;
  "notifications.status.provider_accepted": undefined;
  "notifications.ticket.update.body": undefined;
  "notifications.ticket.update.title": undefined;
  "ops.emergency.contacts": undefined;
  "ops.emergency.do_not_attempt_repair": undefined;
  "ops.emergency.follow_site_procedure": undefined;
  "ops.emergency.no_rescue_guarantee": undefined;
  "ops.emergency.not_configured": undefined;
  "ops.emergency.qualified_contractor_only": undefined;
  "ops.emergency.title": undefined;
  "ops.helpdesk.category.civil": undefined;
  "ops.helpdesk.category.cleaning": undefined;
  "ops.helpdesk.category.common_area": undefined;
  "ops.helpdesk.category.electrical": undefined;
  "ops.helpdesk.category.fire_safety": undefined;
  "ops.helpdesk.category.garden": undefined;
  "ops.helpdesk.category.gas": undefined;
  "ops.helpdesk.category.lift": undefined;
  "ops.helpdesk.category.noise": undefined;
  "ops.helpdesk.category.other": undefined;
  "ops.helpdesk.category.parking": undefined;
  "ops.helpdesk.category.pest": undefined;
  "ops.helpdesk.category.plumbing": undefined;
  "ops.helpdesk.category.security": undefined;
  "ops.helpdesk.category.support_privacy": undefined;
  "ops.helpdesk.category.water_supply": undefined;
  "ops.helpdesk.closure.auto_close": { hours: string | number };
  "ops.helpdesk.closure.confirm_prompt": undefined;
  "ops.helpdesk.duplicate.possible": undefined;
  "ops.helpdesk.form.confirm_before_submit": undefined;
  "ops.helpdesk.form.description": undefined;
  "ops.helpdesk.form.photos": undefined;
  "ops.helpdesk.form.save_draft": undefined;
  "ops.helpdesk.form.submit": undefined;
  "ops.helpdesk.form.title": undefined;
  "ops.helpdesk.form.unsafe_question": undefined;
  "ops.helpdesk.priority.emergency": undefined;
  "ops.helpdesk.priority.low": undefined;
  "ops.helpdesk.priority.normal": undefined;
  "ops.helpdesk.priority.urgent": undefined;
  "ops.helpdesk.reason.approver_required": undefined;
  "ops.helpdesk.reason.contractor_required": undefined;
  "ops.helpdesk.reason.merge_scope_mismatch": undefined;
  "ops.helpdesk.reopen.window_passed": undefined;
  "ops.helpdesk.reopen.within_days": { days: string | number };
  "ops.helpdesk.routing.contractor": undefined;
  "ops.helpdesk.scope.block": undefined;
  "ops.helpdesk.scope.common_hint": undefined;
  "ops.helpdesk.scope.private": undefined;
  "ops.helpdesk.scope.private_hint": undefined;
  "ops.helpdesk.scope.society": undefined;
  "ops.helpdesk.state.assigned": undefined;
  "ops.helpdesk.state.awaiting_material": undefined;
  "ops.helpdesk.state.awaiting_resident": undefined;
  "ops.helpdesk.state.cancelled": undefined;
  "ops.helpdesk.state.closed": undefined;
  "ops.helpdesk.state.draft": undefined;
  "ops.helpdesk.state.in_progress": undefined;
  "ops.helpdesk.state.open": undefined;
  "ops.helpdesk.state.reopened": undefined;
  "ops.helpdesk.state.resolved": undefined;
  "ops.helpdesk.state.submitted": undefined;
  "ops.helpdesk.state.triaged": undefined;
  "ops.helpdesk.state.waiting_resident": undefined;
  "ops.helpdesk.support.available_always": undefined;
  "ops.helpdesk.support.title": undefined;
  "ops.sla.ack_target": { minutes: string | number };
  "ops.sla.breached": { hours: string | number };
  "ops.sla.due_in": { hours: string | number };
  "ops.sla.on_track": undefined;
  "ops.sla.pause_reason.awaiting_material": undefined;
  "ops.sla.pause_reason.awaiting_resident": undefined;
  "ops.sla.paused": { reason: string | number };
  "ops.sla.pilot_default": undefined;
  "parcels.consent.leave_at_gate": undefined;
  "parcels.consent.required_for_leave_at_gate": undefined;
  "parcels.consent.revoke_too_late": undefined;
  "parcels.custody.courier_says_delivered": undefined;
  "parcels.custody.gate_entry_is_not_delivery": undefined;
  "parcels.custody.in_society_custody": undefined;
  "parcels.custody.not_in_custody": undefined;
  "parcels.expectation.brand": { brand: string | number };
  "parcels.expectation.window": { from: string | number; until: string | number };
  "parcels.pickup.denied.already_collected": undefined;
  "parcels.pickup.denied.delegation_required": undefined;
  "parcels.pickup.denied.invalid_token": undefined;
  "parcels.pickup.denied.screenshot_not_accepted": undefined;
  "parcels.pickup.denied.supervision_required": undefined;
  "parcels.pickup.denied.token_expired": undefined;
  "parcels.pickup.single_use": undefined;
  "parcels.pickup.token_instruction": { hours: string | number };
  "parcels.reminder.h24": { unit: string | number };
  "parcels.reminder.h48": { unit: string | number };
  "parcels.report.physical_over": { n: string | number };
  "parcels.report.physical_short": { n: string | number };
  "parcels.report.reconciled": { n: string | number };
  "parcels.state.cancelled": undefined;
  "parcels.state.collected": undefined;
  "parcels.state.expected": undefined;
  "parcels.state.lost_exception": undefined;
  "parcels.state.pickup_pending": undefined;
  "parcels.state.received_at_gate": undefined;
  "parcels.state.refused": undefined;
  "parcels.state.returned": undefined;
  "parcels.state.stored": undefined;
  "resident.approval.approve": undefined;
  "resident.approval.deny": undefined;
  "resident.approval.not_entered_note": undefined;
  "resident.approval.visitor_at_gate": { visitor: string | number };
  "resident.fallback.call_guard": undefined;
  "resident.fallback.call_note": undefined;
  "resident.home.action.approve": undefined;
  "resident.home.action.invite": undefined;
  "resident.home.action.pay_dues": undefined;
  "resident.home.action.report_issue": undefined;
  "resident.home.operational_messages": undefined;
  "resident.home.pending_approval": undefined;
  "resident.home.title": undefined;
  "resident.state.empty": undefined;
  "resident.state.expired": undefined;
  "resident.state.loading": undefined;
  "resident.state.offline": undefined;
  "resident.state.permission_denied": undefined;
  "resident.support.raise": undefined;
  "shifts.checklist.battery": undefined;
  "shifts.checklist.end.title": undefined;
  "shifts.checklist.inside_records": undefined;
  "shifts.checklist.keys": undefined;
  "shifts.checklist.network": undefined;
  "shifts.checklist.never_blocks": undefined;
  "shifts.checklist.parcels_counted": { n: string | number };
  "shifts.checklist.parcels_in_custody": undefined;
  "shifts.checklist.pending_visits": undefined;
  "shifts.checklist.policy_age": undefined;
  "shifts.checklist.relay_health": undefined;
  "shifts.checklist.sensor_health": undefined;
  "shifts.checklist.start.title": undefined;
  "shifts.checklist.status.attention": undefined;
  "shifts.checklist.status.not_reported": undefined;
  "shifts.checklist.status.ok": undefined;
  "shifts.checklist.unresolved_incidents": undefined;
  "shifts.handover.ack.incoming": undefined;
  "shifts.handover.ack.outgoing": undefined;
  "shifts.handover.ack.supervisor": undefined;
  "shifts.handover.both_or_supervisor": undefined;
  "shifts.handover.escalated_note": undefined;
  "shifts.handover.list_truncated": { listed: string | number; total: string | number };
  "shifts.handover.open_items_count": { n: string | number };
  "shifts.handover.open_items_title": undefined;
  "shifts.handover.state.acknowledged": undefined;
  "shifts.handover.state.escalated": undefined;
  "shifts.handover.state.pending": undefined;
  "shifts.handover.summary_advisory": undefined;
  "shifts.handover.title": undefined;
  "shifts.item.incident_unresolved": undefined;
  "shifts.item.override_active": undefined;
  "shifts.item.parcel_in_custody": undefined;
  "shifts.item.visit_inside": undefined;
  "shifts.item.visit_pending_decision": undefined;
  "shifts.language.kannada_later": undefined;
  "shifts.language.label": undefined;
  "shifts.override.expires_at_shift_end": undefined;
  "shifts.training.completed": undefined;
  "shifts.training.missing": { n: string | number };
  "shifts.training.practice_mode": undefined;
  "shifts.training.scenario.cab_entry": undefined;
  "shifts.training.scenario.delivery_entry": undefined;
  "shifts.training.scenario.emergency_entry": undefined;
  "shifts.training.scenario.guest_entry": undefined;
  "shifts.training.scenario.incident_report": undefined;
  "shifts.training.scenario.parcel_pickup": undefined;
  "shifts.training.scenario.parcel_receive": undefined;
  "shifts.training.scenario.service_entry": undefined;
  "shifts.training.scenario.shift_handover": undefined;
  "shifts.training.scenario.staff_checkin": undefined;
  "staff.attendance.check_in_with": undefined;
  "staff.attendance.correction": { reason: string | number; who: string | number };
  "staff.attendance.direction.in": undefined;
  "staff.attendance.direction.out": undefined;
  "staff.attendance.observation_note": undefined;
  "staff.attendance.recorded": undefined;
  "staff.consent.body": undefined;
  "staff.consent.required_first": undefined;
  "staff.consent.staff_action": undefined;
  "staff.consent.title": undefined;
  "staff.consent.withdrawn": undefined;
  "staff.engagement.authorised_now": { unit: string | number };
  "staff.engagement.ended": { unit: string | number };
  "staff.engagement.hours": { days: string | number; from: string | number; to: string | number };
  "staff.engagement.outside_hours": undefined;
  "staff.id.masked": { masked: string | number };
  "staff.payroll.amount": { amount: string | number };
  "staff.payroll.approved": undefined;
  "staff.payroll.needs_household_approval": undefined;
  "staff.payroll.proposed": undefined;
  "staff.payroll.rejected": undefined;
  "staff.police.expired": undefined;
  "staff.police.not_recorded": undefined;
  "staff.police.not_verified": undefined;
  "staff.police.requested": undefined;
  "staff.police.verified": undefined;
  "states.local.saved_awaiting_sync": undefined;
  "states.local.synced": undefined;
  "states.parcel.at_gate": undefined;
  "states.parcel.handed_over": undefined;
  "states.payment.paid": undefined;
  "states.payment.received_settlement_pending": undefined;
  "states.payment.settled": undefined;
  "states.visit.approved": undefined;
  "states.visit.denied": undefined;
  "states.visit.entered": undefined;
  "states.visit.expired": undefined;
  "states.visit.no_response": undefined;
  "states.visit.submitted": undefined;
  "visitor.consent.accept": undefined;
  "visitor.consent.decline": undefined;
  "visitor.consent.title": undefined;
  "visitor.notice.body": undefined;
  "visitor.notice.title": undefined;
  "visitor.pass.expired": undefined;
  "visitor.pass.expiry": { time: string | number };
  "visitor.rights.link": undefined;
}

export type I18nKey = keyof KeyParams;

export const ALL_KEYS: readonly I18nKey[] = [
  "ai.complaint.choose_location",
  "ai.complaint.confirm_location",
  "ai.complaint.consent_speech",
  "ai.complaint.emergency",
  "ai.complaint.limit_60s",
  "ai.fallback.budget_exhausted",
  "ai.fallback.kill_switch",
  "ai.fallback.not_enabled",
  "ai.fallback.ordinary_path",
  "ai.feature.bill_anomaly",
  "ai.feature.complaint",
  "ai.feature.handover",
  "ai.feature.notice",
  "ai.feature.notification_health",
  "ai.feature.poll",
  "ai.feature.translation",
  "ai.feature.triage",
  "ai.label.ai_draft",
  "ai.label.correction",
  "ai.label.declining",
  "ai.label.human_review",
  "ai.label.original_text",
  "ai.label.reasons",
  "ai.label.simulation",
  "ai.label.sources",
  "ai.label.what_will_be_saved",
  "ai.notice.needs_approval",
  "ai.notice.threat_flag",
  "ai.notification_health.disclaimer",
  "ai.promise.no_ads",
  "ai.promise.no_gate",
  "ai.promise.no_money",
  "ai.promise.no_training",
  "ai.proposal.confirm",
  "ai.proposal.confirmed",
  "ai.proposal.discard",
  "ai.proposal.edit",
  "ai.proposal.expired",
  "ai.proposal.preview_title",
  "ai.proposal.stale",
  "ai.translation.legal_review",
  "ai.translation.original_shown",
  "common.action.back",
  "common.action.call",
  "common.action.cancel",
  "common.action.close",
  "common.action.confirm",
  "common.action.done",
  "common.action.help",
  "common.action.next",
  "common.action.ok",
  "common.action.retry",
  "common.action.save",
  "common.action.sign_out",
  "common.answer.no",
  "common.answer.yes",
  "common.app.name",
  "common.language.en",
  "common.language.hi",
  "common.language.label",
  "common.language.mr",
  "common.status.loading",
  "common.time.just_now",
  "common.time.minutes_ago",
  "common.unit.label",
  "community.document.access.all_residents",
  "community.document.access.committee",
  "community.document.access.managers",
  "community.document.access.owners",
  "community.document.authority",
  "community.document.download.expires",
  "community.document.effective_from",
  "community.document.scan.clean",
  "community.document.scan.infected",
  "community.document.scan.simulation",
  "community.document.scan.unavailable",
  "community.document.sha256",
  "community.document.type.audit_report",
  "community.document.type.bye_laws",
  "community.document.type.circular",
  "community.document.type.minutes",
  "community.document.type.other",
  "community.document.type.policy",
  "community.document.upload.unsupported",
  "community.emergency.channel",
  "community.emergency.no_ads",
  "community.emergency.rate_limited",
  "community.notice.acknowledge",
  "community.notice.ai_draft.label",
  "community.notice.ai_draft.needs_approval",
  "community.notice.audience.block",
  "community.notice.audience.role",
  "community.notice.audience.society",
  "community.notice.audience.unit",
  "community.notice.kind.emergency",
  "community.notice.kind.general",
  "community.notice.kind.legal",
  "community.notice.kind.safety",
  "community.notice.original",
  "community.notice.published_immutable",
  "community.notice.state.approved",
  "community.notice.state.archived",
  "community.notice.state.draft",
  "community.notice.state.published",
  "community.notice.state.scheduled",
  "community.notice.state.superseded",
  "community.notice.translation.machine_drafted",
  "community.notice.translation.review_required",
  "community.notice.translation.reviewed",
  "community.notice.translation.unreviewed",
  "community.poll.answered",
  "community.poll.non_binding",
  "community.poll.non_binding_hint",
  "community.poll.owners_only",
  "community.poll.state.closed",
  "community.poll.state.draft",
  "community.poll.state.open",
  "community.poll.visibility.after_close",
  "community.poll.visibility.live",
  "community.poll.visibility.managers_only",
  "community.poll.wording.flagged",
  "consent.review.flag",
  "consent.stub.consent.body",
  "consent.stub.consent.title",
  "consent.stub.notice.body",
  "consent.stub.notice.title",
  "errors.already_decided",
  "errors.dependency_unavailable",
  "errors.duplicate_payload_mismatch",
  "errors.invalid_schema",
  "errors.legal_pack_not_approved",
  "errors.missing_tax_config",
  "errors.not_authorised",
  "errors.not_found",
  "errors.policy_violation",
  "errors.rate_limited",
  "errors.request_expired",
  "errors.request_id.label",
  "errors.stale_version",
  "errors.unauthenticated",
  "errors.unknown",
  "finance.action.pay_now",
  "finance.bill.due",
  "finance.bill.title",
  "finance.essential_services.note",
  "finance.receipt.number",
  "finance.receipt.title",
  "finance.settlement.failed",
  "finance.settlement.pending",
  "finance.settlement.settled",
  "finance.status.paid",
  "finance.status.partially_paid",
  "finance.status.unpaid",
  "guard.banner.offline",
  "guard.banner.online",
  "guard.banner.policy_age",
  "guard.banner.policy_stale",
  "guard.commit.saved",
  "guard.decision.allow",
  "guard.decision.deny",
  "guard.handover.check_parcel",
  "guard.handover.check_person",
  "guard.handover.check_unit",
  "guard.handover.confirm",
  "guard.handover.title",
  "guard.incident.emergency",
  "guard.incident.report",
  "guard.nav.incident",
  "guard.nav.inside",
  "guard.nav.parcels",
  "guard.nav.scan",
  "guard.nav.shift",
  "guard.queue.empty",
  "guard.queue.pending",
  "guard.shift.end",
  "guard.shift.start",
  "guard.tile.delivery",
  "guard.tile.guest",
  "guard.tile.service",
  "guard.training.banner",
  "guard.training.complete",
  "guard.training.scenario.emergency",
  "guard.training.scenario.invited_visitor",
  "guard.training.scenario.no_response",
  "guard.training.scenario.outage",
  "guard.training.scenario.unannounced_guest",
  "guard.visitor.call_resident",
  "guard.visitor.no_response",
  "guard.visitor.waiting_approval",
  "notifications.approval.action.already_decided",
  "notifications.approval.action.expired",
  "notifications.approval.decided.body",
  "notifications.approval.decided.title",
  "notifications.approval.escalation.body",
  "notifications.approval.escalation.title",
  "notifications.approval.expired.body",
  "notifications.approval.expired.title",
  "notifications.approval.guard_options.title",
  "notifications.approval.ivr.prompt",
  "notifications.approval.link.sms",
  "notifications.approval.link.whatsapp",
  "notifications.approval.request.body",
  "notifications.approval.request.lockscreen.body",
  "notifications.approval.request.lockscreen.title",
  "notifications.approval.request.title",
  "notifications.channel.emergency.title",
  "notifications.channel.security.description",
  "notifications.diag.apple.focus_allow",
  "notifications.diag.apple.time_sensitive",
  "notifications.diag.common.battery",
  "notifications.diag.common.permission",
  "notifications.diag.common.test_push",
  "notifications.diag.disclaimer.no_guarantee",
  "notifications.diag.oppo.app_launch",
  "notifications.diag.oppo.battery",
  "notifications.diag.samsung.battery",
  "notifications.diag.samsung.sleeping_apps",
  "notifications.diag.verdict.cannot_tell",
  "notifications.diag.verdict.needs_attention",
  "notifications.diag.verdict.no_problem_found",
  "notifications.diag.vivo.autostart",
  "notifications.diag.vivo.background_power",
  "notifications.diag.xiaomi.autostart",
  "notifications.diag.xiaomi.battery",
  "notifications.diag.xiaomi.lock_recents",
  "notifications.digest.weekly.body",
  "notifications.digest.weekly.title",
  "notifications.emergency.alert.body",
  "notifications.emergency.alert.title",
  "notifications.fallback.call",
  "notifications.fallback.intercom",
  "notifications.fallback.provider_outage",
  "notifications.finance.notice.body",
  "notifications.finance.notice.title",
  "notifications.option.deny",
  "notifications.option.hold",
  "notifications.option.intercom",
  "notifications.option.leave_at_gate",
  "notifications.option.lobby_only",
  "notifications.setting.show_identity_lockscreen",
  "notifications.status.actioned",
  "notifications.status.app_received",
  "notifications.status.created",
  "notifications.status.displayed",
  "notifications.status.expired",
  "notifications.status.provider_accepted",
  "notifications.ticket.update.body",
  "notifications.ticket.update.title",
  "ops.emergency.contacts",
  "ops.emergency.do_not_attempt_repair",
  "ops.emergency.follow_site_procedure",
  "ops.emergency.no_rescue_guarantee",
  "ops.emergency.not_configured",
  "ops.emergency.qualified_contractor_only",
  "ops.emergency.title",
  "ops.helpdesk.category.civil",
  "ops.helpdesk.category.cleaning",
  "ops.helpdesk.category.common_area",
  "ops.helpdesk.category.electrical",
  "ops.helpdesk.category.fire_safety",
  "ops.helpdesk.category.garden",
  "ops.helpdesk.category.gas",
  "ops.helpdesk.category.lift",
  "ops.helpdesk.category.noise",
  "ops.helpdesk.category.other",
  "ops.helpdesk.category.parking",
  "ops.helpdesk.category.pest",
  "ops.helpdesk.category.plumbing",
  "ops.helpdesk.category.security",
  "ops.helpdesk.category.support_privacy",
  "ops.helpdesk.category.water_supply",
  "ops.helpdesk.closure.auto_close",
  "ops.helpdesk.closure.confirm_prompt",
  "ops.helpdesk.duplicate.possible",
  "ops.helpdesk.form.confirm_before_submit",
  "ops.helpdesk.form.description",
  "ops.helpdesk.form.photos",
  "ops.helpdesk.form.save_draft",
  "ops.helpdesk.form.submit",
  "ops.helpdesk.form.title",
  "ops.helpdesk.form.unsafe_question",
  "ops.helpdesk.priority.emergency",
  "ops.helpdesk.priority.low",
  "ops.helpdesk.priority.normal",
  "ops.helpdesk.priority.urgent",
  "ops.helpdesk.reason.approver_required",
  "ops.helpdesk.reason.contractor_required",
  "ops.helpdesk.reason.merge_scope_mismatch",
  "ops.helpdesk.reopen.window_passed",
  "ops.helpdesk.reopen.within_days",
  "ops.helpdesk.routing.contractor",
  "ops.helpdesk.scope.block",
  "ops.helpdesk.scope.common_hint",
  "ops.helpdesk.scope.private",
  "ops.helpdesk.scope.private_hint",
  "ops.helpdesk.scope.society",
  "ops.helpdesk.state.assigned",
  "ops.helpdesk.state.awaiting_material",
  "ops.helpdesk.state.awaiting_resident",
  "ops.helpdesk.state.cancelled",
  "ops.helpdesk.state.closed",
  "ops.helpdesk.state.draft",
  "ops.helpdesk.state.in_progress",
  "ops.helpdesk.state.open",
  "ops.helpdesk.state.reopened",
  "ops.helpdesk.state.resolved",
  "ops.helpdesk.state.submitted",
  "ops.helpdesk.state.triaged",
  "ops.helpdesk.state.waiting_resident",
  "ops.helpdesk.support.available_always",
  "ops.helpdesk.support.title",
  "ops.sla.ack_target",
  "ops.sla.breached",
  "ops.sla.due_in",
  "ops.sla.on_track",
  "ops.sla.pause_reason.awaiting_material",
  "ops.sla.pause_reason.awaiting_resident",
  "ops.sla.paused",
  "ops.sla.pilot_default",
  "parcels.consent.leave_at_gate",
  "parcels.consent.required_for_leave_at_gate",
  "parcels.consent.revoke_too_late",
  "parcels.custody.courier_says_delivered",
  "parcels.custody.gate_entry_is_not_delivery",
  "parcels.custody.in_society_custody",
  "parcels.custody.not_in_custody",
  "parcels.expectation.brand",
  "parcels.expectation.window",
  "parcels.pickup.denied.already_collected",
  "parcels.pickup.denied.delegation_required",
  "parcels.pickup.denied.invalid_token",
  "parcels.pickup.denied.screenshot_not_accepted",
  "parcels.pickup.denied.supervision_required",
  "parcels.pickup.denied.token_expired",
  "parcels.pickup.single_use",
  "parcels.pickup.token_instruction",
  "parcels.reminder.h24",
  "parcels.reminder.h48",
  "parcels.report.physical_over",
  "parcels.report.physical_short",
  "parcels.report.reconciled",
  "parcels.state.cancelled",
  "parcels.state.collected",
  "parcels.state.expected",
  "parcels.state.lost_exception",
  "parcels.state.pickup_pending",
  "parcels.state.received_at_gate",
  "parcels.state.refused",
  "parcels.state.returned",
  "parcels.state.stored",
  "resident.approval.approve",
  "resident.approval.deny",
  "resident.approval.not_entered_note",
  "resident.approval.visitor_at_gate",
  "resident.fallback.call_guard",
  "resident.fallback.call_note",
  "resident.home.action.approve",
  "resident.home.action.invite",
  "resident.home.action.pay_dues",
  "resident.home.action.report_issue",
  "resident.home.operational_messages",
  "resident.home.pending_approval",
  "resident.home.title",
  "resident.state.empty",
  "resident.state.expired",
  "resident.state.loading",
  "resident.state.offline",
  "resident.state.permission_denied",
  "resident.support.raise",
  "shifts.checklist.battery",
  "shifts.checklist.end.title",
  "shifts.checklist.inside_records",
  "shifts.checklist.keys",
  "shifts.checklist.network",
  "shifts.checklist.never_blocks",
  "shifts.checklist.parcels_counted",
  "shifts.checklist.parcels_in_custody",
  "shifts.checklist.pending_visits",
  "shifts.checklist.policy_age",
  "shifts.checklist.relay_health",
  "shifts.checklist.sensor_health",
  "shifts.checklist.start.title",
  "shifts.checklist.status.attention",
  "shifts.checklist.status.not_reported",
  "shifts.checklist.status.ok",
  "shifts.checklist.unresolved_incidents",
  "shifts.handover.ack.incoming",
  "shifts.handover.ack.outgoing",
  "shifts.handover.ack.supervisor",
  "shifts.handover.both_or_supervisor",
  "shifts.handover.escalated_note",
  "shifts.handover.list_truncated",
  "shifts.handover.open_items_count",
  "shifts.handover.open_items_title",
  "shifts.handover.state.acknowledged",
  "shifts.handover.state.escalated",
  "shifts.handover.state.pending",
  "shifts.handover.summary_advisory",
  "shifts.handover.title",
  "shifts.item.incident_unresolved",
  "shifts.item.override_active",
  "shifts.item.parcel_in_custody",
  "shifts.item.visit_inside",
  "shifts.item.visit_pending_decision",
  "shifts.language.kannada_later",
  "shifts.language.label",
  "shifts.override.expires_at_shift_end",
  "shifts.training.completed",
  "shifts.training.missing",
  "shifts.training.practice_mode",
  "shifts.training.scenario.cab_entry",
  "shifts.training.scenario.delivery_entry",
  "shifts.training.scenario.emergency_entry",
  "shifts.training.scenario.guest_entry",
  "shifts.training.scenario.incident_report",
  "shifts.training.scenario.parcel_pickup",
  "shifts.training.scenario.parcel_receive",
  "shifts.training.scenario.service_entry",
  "shifts.training.scenario.shift_handover",
  "shifts.training.scenario.staff_checkin",
  "staff.attendance.check_in_with",
  "staff.attendance.correction",
  "staff.attendance.direction.in",
  "staff.attendance.direction.out",
  "staff.attendance.observation_note",
  "staff.attendance.recorded",
  "staff.consent.body",
  "staff.consent.required_first",
  "staff.consent.staff_action",
  "staff.consent.title",
  "staff.consent.withdrawn",
  "staff.engagement.authorised_now",
  "staff.engagement.ended",
  "staff.engagement.hours",
  "staff.engagement.outside_hours",
  "staff.id.masked",
  "staff.payroll.amount",
  "staff.payroll.approved",
  "staff.payroll.needs_household_approval",
  "staff.payroll.proposed",
  "staff.payroll.rejected",
  "staff.police.expired",
  "staff.police.not_recorded",
  "staff.police.not_verified",
  "staff.police.requested",
  "staff.police.verified",
  "states.local.saved_awaiting_sync",
  "states.local.synced",
  "states.parcel.at_gate",
  "states.parcel.handed_over",
  "states.payment.paid",
  "states.payment.received_settlement_pending",
  "states.payment.settled",
  "states.visit.approved",
  "states.visit.denied",
  "states.visit.entered",
  "states.visit.expired",
  "states.visit.no_response",
  "states.visit.submitted",
  "visitor.consent.accept",
  "visitor.consent.decline",
  "visitor.consent.title",
  "visitor.notice.body",
  "visitor.notice.title",
  "visitor.pass.expired",
  "visitor.pass.expiry",
  "visitor.rights.link"
];
